### ISSUE TITLE
Adapting for new V5 skills api

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/lambda-member-v5user-skill-sync#6]
Done via:
https://github.com/topcoder-platform/lambda-member-v5user-skill-sync/pull/5

**Comment by SathyaJayabal** [comment]
verified on  dev. Skills added/removed from the profile settings page reflect on the  taas-app FE(which uses the new skills api)
<img width="1440" alt="Screenshot 2021-08-18 at 11 02 48 AM" src="https://user-images.githubusercontent.com/58783823/129842956-9e9d8eb4-f454-4a0c-bc10-25703a787f78.png">

cc @vikasrohit 
<img width="1440" alt="Screenshot 2021-08-18 at 11 03 42 AM" src="https://user-images.githubusercontent.com/58783823/129842970-74fdb5ac-c16e-4f29-9cec-966871ad0e95.png">

**Comment by vikasrohit** [comment]
@sachin-maheshwari I guess we can now merge #5

**Comment by sandhiyakavi** [comment]
@vikasrohit I added two skills before setting Env variables in Prod. Then it was removed. But it's still displaying.
![image](https://user-images.githubusercontent.com/55895538/130064008-90330b54-d652-4569-ac0a-ea8a04e020a2.png)
![image](https://user-images.githubusercontent.com/55895538/130064050-637fed05-d04d-455d-8451-33dc03c7f52f.png)

After setting Env variables. I added skills Spring Boot and Jmeter , those were added and removed correctly.
![image](https://user-images.githubusercontent.com/55895538/130062739-3e3c863b-f30d-480a-ae4b-f21b5e055b71.png)
![image](https://user-images.githubusercontent.com/55895538/130062886-8fe41c32-eb7b-4bca-be6d-77f27c60068a.png)
![image](https://user-images.githubusercontent.com/55895538/130063005-1e0e6b6e-e565-4083-9361-82d30e150f24.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. Skills are getting added and removed correctly.
![image](https://user-images.githubusercontent.com/55895538/130062739-3e3c863b-f30d-480a-ae4b-f21b5e055b71.png)
![image](https://user-images.githubusercontent.com/55895538/130062886-8fe41c32-eb7b-4bca-be6d-77f27c60068a.png)
![image](https://user-images.githubusercontent.com/55895538/130063005-1e0e6b6e-e565-4083-9361-82d30e150f24.png)
